"""add_waypoints_route_geojson_to_events

Revision ID: 80cb41d10465
Revises: 9ac29ed3c177
Create Date: 2026-05-29 13:03:12.596835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80cb41d10465'
down_revision: Union[str, None] = '9ac29ed3c177'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('waypoints', sa.JSON(), nullable=True))
    op.add_column('events', sa.Column('route_geojson', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'route_geojson')
    op.drop_column('events', 'waypoints')
    # ### end Alembic commands ###
